### ISSUE TITLE
Will Not Load

### ISSUE THREAD

**Issue by Drakma** [Axieum/PedestalCrafting#1] opened 2018-07-03 20:07 UTC
I can't get any pack to load with this mod.  I have tried multiple times.

https://pastebin.com/7HeAATZ0

    Minecraft Version: 1.12.2
    Java Version: 1.8.0_131, Oracle Corporation
    Forge 14.23.4.2727

**Comment by Axieum** [comment] 2018-07-04 04:49
Thank you for the report, I'm currently working to fix this. I believe it is due to me forgetting to tell my mod to load _after_ The One Probe. Expect this to be fixed in the next update!

**Comment by Axieum** [comment] 2018-07-04 05:15
This issue is fixed in the latest release (https://github.com/Axieum/PedestalCrafting/releases/tag/v1.0.1).

Thank you for the report!

**Comment by darkphan** [comment] 2018-07-04 15:37
This still happens if you do have The One Probe installed.

**Comment by Drakma** [comment] 2018-07-04 17:45
For what it's worth if pedestal and craft tweaker are the only mods installed in the pack it will not load and this error still occurs.

**Comment by Drakma** [comment] 2018-07-05 04:10
Just came back to say I "just" got it working.  It was my bad.  The mod hadn't updated.  

Looks great!

**Comment by Axieum** [comment] 2018-07-05 05:01
That's great to hear! I was honestly scratching my head as to why it wouldn't work still.

**Comment by darkphan** [comment] 2018-07-05 21:50
The problem is the mod has a dependency on The One Probe and crashes if TOP is not installed. Not all modpack devs like to use TOP :/

**Comment by Axieum** [comment] 2018-07-06 04:14
Thanks for the heads up! Fixed in version `1.0.2`.

**Closed by Axieum** 2018-07-06 04:14 UTC
Labels: bug
